"""Fallback catalog used when MongoDB data is unavailable."""

from copy import deepcopy


MOCK_PRODUCTS = [
    {
        "_id": "mock-1",
        "name": "Ivory Structured Blazer",
        "brand": "DressMate Studio",
        "price": "2499",
        "colour": "ivory",
        "product_type": "jacket",
        "description": "Tailored blazer with a clean silhouette for polished day looks.",
        "image_url": "https://placehold.co/600x800/F3EDE2/5A4637?text=Ivory+Blazer",
        "rating": 4.7,
        "style_tags": ["formal", "minimalist", "office"],
        "recommended_skin_tones": ["fair", "light", "medium"],
        "recommended_body_shapes": ["rectangle", "hourglass", "pear"],
    },
    {
        "_id": "mock-2",
        "name": "Emerald Wrap Dress",
        "brand": "DressMate Studio",
        "price": "2199",
        "colour": "green",
        "product_type": "dress",
        "description": "Wrap dress that defines the waist and works for festive evenings.",
        "image_url": "https://placehold.co/600x800/0F766E/F8FAFC?text=Emerald+Dress",
        "rating": 4.8,
        "style_tags": ["party", "formal", "dress"],
        "recommended_skin_tones": ["medium", "warm", "tan", "deep"],
        "recommended_body_shapes": ["hourglass", "pear", "apple"],
    },
    {
        "_id": "mock-3",
        "name": "Rose Kurta Set",
        "brand": "Anaya",
        "price": "1899",
        "colour": "pink",
        "product_type": "kurta",
        "description": "Soft festive kurta set with subtle embroidery and easy drape.",
        "image_url": "https://placehold.co/600x800/F9A8D4/4A044E?text=Rose+Kurta",
        "rating": 4.6,
        "style_tags": ["ethnic", "kurta", "festive"],
        "recommended_skin_tones": ["fair", "medium", "tan"],
        "recommended_body_shapes": ["pear", "rectangle", "hourglass"],
    },
    {
        "_id": "mock-4",
        "name": "Classic Indigo Jeans",
        "brand": "Urban Loop",
        "price": "1499",
        "colour": "blue",
        "product_type": "jeans",
        "description": "Straight fit denim that anchors casual and streetwear outfits.",
        "image_url": "https://placehold.co/600x800/1D4ED8/F8FAFC?text=Indigo+Jeans",
        "rating": 4.5,
        "style_tags": ["casual", "streetwear", "minimalist"],
        "recommended_skin_tones": ["fair", "light", "medium", "tan", "deep"],
        "recommended_body_shapes": ["rectangle", "apple", "hourglass"],
    },
    {
        "_id": "mock-5",
        "name": "Terracotta Co-ord Set",
        "brand": "Sable Edit",
        "price": "2699",
        "colour": "orange",
        "product_type": "top",
        "description": "Relaxed co-ord set in a warm earthy tone for elevated casual wear.",
        "image_url": "https://placehold.co/600x800/C2410C/FFF7ED?text=Co-ord+Set",
        "rating": 4.4,
        "style_tags": ["casual", "boho", "minimalist"],
        "recommended_skin_tones": ["warm", "tan", "deep"],
        "recommended_body_shapes": ["rectangle", "apple", "pear"],
    },
    {
        "_id": "mock-6",
        "name": "Midnight Saree",
        "brand": "Aster Loom",
        "price": "3299",
        "colour": "black",
        "product_type": "saree",
        "description": "Fluid saree with understated shine for elegant evening styling.",
        "image_url": "https://placehold.co/600x800/111827/F8FAFC?text=Midnight+Saree",
        "rating": 4.9,
        "style_tags": ["ethnic", "formal", "party"],
        "recommended_skin_tones": ["medium", "tan", "deep"],
        "recommended_body_shapes": ["hourglass", "pear", "rectangle"],
    },
    {
        "_id": "mock-7",
        "name": "Cloud White Shirt",
        "brand": "North Thread",
        "price": "1299",
        "colour": "white",
        "product_type": "shirt",
        "description": "Crisp shirt for office layers and minimalist weekend dressing.",
        "image_url": "https://placehold.co/600x800/F8FAFC/334155?text=White+Shirt",
        "rating": 4.3,
        "style_tags": ["formal", "minimalist", "casual"],
        "recommended_skin_tones": ["fair", "light", "medium"],
        "recommended_body_shapes": ["rectangle", "apple", "inverted triangle"],
    },
    {
        "_id": "mock-8",
        "name": "Lavender Occasion Gown",
        "brand": "Velora",
        "price": "3899",
        "colour": "purple",
        "product_type": "dress",
        "description": "Flowing gown with a soft sheen and balanced volume through the skirt.",
        "image_url": "https://placehold.co/600x800/A855F7/F5F3FF?text=Lavender+Gown",
        "rating": 4.7,
        "style_tags": ["party", "formal", "dress"],
        "recommended_skin_tones": ["fair", "medium", "deep"],
        "recommended_body_shapes": ["pear", "hourglass", "apple"],
    },
]


def get_mock_products():
    return deepcopy(MOCK_PRODUCTS)
